<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>foldingStartMarker</key>
	<string>‌</string>
	<key>foldingStopMarker</key>
	<string>‍</string>
	<key>name</key>
	<string>Command Output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.header.shebang</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.section</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*\w+\:)(.*)$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=‌)</string>
			<key>comment</key>
			<string>script-output body</string>
			<key>end</key>
			<string>(?=‍)</string>
			<key>name</key>
			<string>output.shebang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#pythonTraceback</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=​)</string>
			<key>comment</key>
			<string>script-started header</string>
			<key>end</key>
			<string>(?=‌)</string>
			<key>name</key>
			<string>comment.header.shebang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)\d+(?=\])</string>
					<key>name</key>
					<string>keyword.pid.shebang</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=‍)</string>
			<key>comment</key>
			<string>script-complete footer</string>
			<key>end</key>
			<string>([\d⓵⓶⓷⓸⓹⓺⓻⓼⓽⓾]+)?(?=⁠)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.section</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([\d\.]*)(?=[hms\'\"])</string>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\d\.]*) ((bytes)|(kb)|(mb)|gb)</string>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>pythonTraceback</key>
		<dict>
			<key>begin</key>
			<string>(Traceback \(most recent call last\):)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=‍)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>match</key>
					<string>File "([^"]+)", line (\d+)(?:, in)?</string>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^([A-Z].*)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.shebang</string>
	<key>uuid</key>
	<string>d763f066-7161-4e49-a979-4f2e70991af3</string>
</dict>
</plist>
